demo6:
  test:
    aaa: 121212
    bbb: 12

demo8.test:
  url: jdbc:mysql://127.0.0.1/user
  username: root
  paasword: 12

username: noear
paasword: 1234

testname: xxx

server.port: 8080

solon.app:
  name: testapp
  group: test

solon.drift: 1

solon.extend: "!app_ext"

solon.locale: "en_US"

solon.cloud.local:
  breaker:
    test: 1
  discovery:
    service:
      local:
        - "http://localhost:8080"
      demo:
        - "http://localhost:8080"
      localrpc:
        - "tcp://localhost:28080"


solon.health.detector: "cpu,disk,jvm,memory,os,qps"


solon.logging.appender:
  console:
    enable: true
  test:
    class: webapp.demox_log_breaker.TestAppender
    level: TRACE

solon.logging.logger:
  "org.apache.*":
    level: INFO
  "org.eclipse.*":
    level: INFO

solon.socketd:
  readBufferSize: "512"
  writeBufferSize: "128"
  connectTimeout: "60s"
  socketTimeout: "60s"


formattest.text: "${solon.socketd.readBufferSize}m/-/${solon.locale}"

server.session:
  timeout: 7200 #单位秒；（可不配，默认：7200）
  state:
    redis:
      server: localhost:6379
      password: 123456
      db: 3
      maxTotaol: 200

#特殊信息输出
solon.output.meta: 1

solon.stop:
  enable: true
  path: /demox/_stop
  host: localhost

solon.quartz.QuartzRun1:
  cron7x: "0 0/1 * * * ? *"
  enable: true

solon.cron4j.Cron4jRun1:
  cron5x: "*/1 * * * *"
  enable: true

custom:
  li:
    - 12
    - 13

app.dict:
  name: 张三
  age: 8
  codes: {dev: "develop", test: "test"}
  likes:
    - 素描
    - 摄影