demo6:
  test:
    aaa: 121212
    bbb: 12

demo8.test:
  url: jdbc:mysql://127.0.0.1/user
  username: root
  paasword: 12

username: noear
paasword: 1234

solon.drift: 1

solon.cloud.local:
  breaker:
    test: 1

solon.logging.appender:
  test:
    class: webapp.demox_mlog.TestAppender
    level: TRACE

solon.socketd:
  readBufferSize: "512"
  writeBufferSize: "128"
  connectTimeout: "60s"
  socketTimeout: "60s"

server.session.state.redis:
  server: localhost:6379
  password: 123456
  db: 3
  maxTotaol: 200

#特殊信息输出
solon.output.meta: 1

solon.stop:
  enabled: true
  path: /demox/_stop
  host: localhost

solon.quartz.QuartzRun1:
  cron7x: "0 0/1 * * * ? *"
  enable: true

solon.cron4j.Cron4jRun1:
  cron5x: "*/1 * * * *"
  enable: true

custom:
  li:
    - 12
    - 13

