###############
# doc links: https://docs.github.com/zh/actions
#----------------------------------------------------------------

name: Solon Features Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀


on: [ push, pull_request, workflow_dispatch ]


jobs:

  test:
    name: Build code and install and test
    env:
      STAGE: BUILD_INSTALL_TEST
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [ '8', '11', '17', '20' ]
    steps:
      # check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # Maven install
      - name: Clean And Install
        run: |
          mvn clean install -Dmaven.test.skip=true --file pom.xml

      # Maven Test
      - name: Test Features
        run: |
          mvn test -Dtest="features.*" -Dmaven.test.failure.ignore=true -f __test/pom.xml

