###############
# doc links: https://docs.github.com/zh/actions
#----------------------------------------------------------------

name: Solon Features Test CI
run-name: ${{ github.actor }} is testing out SOLON in GitHub Actions 🚀


on: [ push, pull_request, workflow_dispatch ]


jobs:

  test:
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    name: Build code and install and test
    env:
      STAGE: BUILD_INSTALL_TEST
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [ '8', '11', '17', '20' ]
    steps:
      # check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # Maven install
      - name: Clean And Install
        run: |
          mvn clean install -Dmaven.test.skip=true --file pom.xml

      # Maven Test
      - name: Test Features
        run: |
          mvn test -Dtest="features.*" -Dmaven.test.failure.ignore=true -f __test/pom.xml

      # Generate test reports
      - name: JEST Test Report JDK version - ${{ matrix.java }}
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests           # Name of the check run which will be created
          fail-on-error: 'false'
          path: ./__test/target/surefire-reports/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results



