name: Release

# Run workflow on commits to the `master` branch
# docs : https://github.com/marketplace/actions/action-maven-publish
# not test!!!
on:
  push:
    branches:
      - master

jobs:

 # Publish package to github package
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/checkout@v3

      - name: Publish to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          run: mvn --batch-mode deploy -DskipTests -Prelease-github
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish package to maven repository
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
#          maven_profiles: 'release-ossrh'
          maven_args: '-DskipTests'
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}